name: my workflow

on:
  workflow_call:
    inputs:
      Param1:
        required: true
        type: string
      Param2:
        required: true
        type: string

jobs:
  print_inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Print params
        run: |
          echo "Param 1: ${{ inputs.Param1 }}"
          echo "Param 2: ${{ inputs.Param2 }}"
